<?php

$events = [
    ["date" => "01/01", "title" => "جشن نوروز", "holiday" => true, "type" => "solar", 'importance' => 1],
    ["date" => "01/02", "title" => "جشن نوروز", "holiday" => true, "type" => "solar", 'importance' => 1],
    ["date" => "01/03", "title" => "جشن نوروز", "holiday" => true, "type" => "solar", 'importance' => 1],
    ["date" => "01/04", "title" => "جشن نوروز", "holiday" => true, "type" => "solar", 'importance' => 1],
    ["date" => "01/06", "title" => "روز امید / روز شادباش‌نویسی", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "01/10", "title" => "جشن آبان‌گاه", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "01/12", "title" => "روز جمهوی اسلامی ایران", "holiday" => true, "type" => "solar", 'importance' => 2],
    ["date" => "01/13", "title" => "جشن سیزده‌به‌در", "holiday" => false, "type" => "solar", 'importance' => 1],
    ["date" => "01/17", "title" => "سروش روز، جشن سروش‌گان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "01/19", "title" => "فروردین روز، جشن فروردین‌گان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "02/02", "title" => "جشن گیاه‌آوری", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "02/03", "title" => "اردیبهشت روز، جشن اردیبهشت‌گان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "02/10", "title" => "جشن چهلم نوروز", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "02/15", "title" => "گاهنبار میدیوزَرِم، جشن میانه بهار، جشن بهاربد / روز پیام‌آوری زرتشت", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "03/01", "title" => "ارغاسوان، جشن گرما", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "03/06", "title" => "خرداد روز، جشن خردادگان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "04/01", "title" => "جشن آب‌پاشونک، جشن آغاز تابستان / سال نو در گاهشماری گاهنباری", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "04/07", "title" => "شهادت دکتر بهشتی", "holiday" => false, "type" => "solar", 'importance' => 2],
    ["date" => "04/06", "title" => "جشن نیلوفر", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "04/13", "title" => "تیرروز، جشن تیرگان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "04/14", "title" => "رحلت امام خمینی", "holiday" => true, "type" => "solar", 'importance' => 1],
    ["date" => "04/15", "title" => "قیام خونین 15 خرداد، جشن خام خواری", "holiday" => true, "type" => "solar", 'importance' => 1],
    ["date" => "05/07", "title" => "مردادروز، جشن مردادگان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "05/10", "title" => "جشن چهلم تابستان", "holiday" => false, "type" => "solar", 'importance' => 2],
    ["date" => "05/15", "title" => "گاهنبار میدیوشِم، جشن میانه تابستان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "05/18", "title" => "جشن مَی‌خواره", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "06/01", "title" => "فغدیه، جشن خنکی هوا", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "06/03", "title" => "جشن کشمین", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "06/04", "title" => "شهریورروز، جشن شهریورگان / زادروز داراب (کوروش) / عروج مانی", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "06/08", "title" => "روز مباررزه با تروریسم، خزان جشن", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "06/15", "title" => "بازار جشن", "holiday" => false, "type" => "solar", 'importance' => 3, 'importance' => 3],
    ["date" => "06/31", "title" => "گاهنبار پَتیَه‌شَهیم، جشن پایان تابستان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "07/01", "title" => "جشن میتراکانا / سال نو هخامنشی", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "07/09", "title" => "آیین قالیشویان اردهال، بازماندی از تیرگان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "07/13", "title" => "تیرروز، جشن تیرروزی", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "07/16", "title" => "مهرروز، جشن مهرگان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "07/21", "title" => "رام روز، جشن رام روزی / جشن پیروزی کاوه و فریدون", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "08/10", "title" => "آبان روز، جشن آبان‌گان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "08/15", "title" => "گاهنبار اَیاثرَم، جشن میانه پاییز", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "09/01", "title" => "آذر جشن", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "09/09", "title" => "آذر روز، جشن آذرگان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "10/01", "title" => "جشن شب یلدا (چله) / گاهنبار میدیارِم، جشن میانه سال گاهنباری و پایان پاییز", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "10/05", "title" => "بازار جشن", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "10/08", "title" => "دی به آذر روز، دومین جشن دی‌گان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "10/14", "title" => "سیر روز، جشن گیاه‌خواری", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "10/15", "title" => "جشن پیکرتراشی / دی به مهر روز، سومین جشن دی‌گان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "10/16", "title" => "جشن درامزینان، جشن درفش‌ها", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "10/23", "title" => "دی به دین روز، چهارمین جشن دی‌گان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "11/01", "title" => "زادروز فردوسی", "holiday" => false, "type" => "solar", 'importance' => 2],
    ["date" => "11/02", "title" => "بهمن روز، جشن بهمن‌گان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "11/04", "title" => "شهریور روز، آغاز پادشاهی داراب (کوروش)", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "11/05", "title" => "جشن نوسَره", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "11/10", "title" => "آبان روز، جشن سَدَه، آتش افروزی بر بام‌ها / نمایش بازی همگانی", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "11/15", "title" => "جشن میانه زمستان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "11/22", "title" => "پیروزی انقلاب اسلامی", "holiday" => true, "type" => "solar", 'importance' => 1],
    ["date" => "12/01", "title" => "جشن اسفندی / جشن آبسالان، بهار جشن / نمایش بازی همگانی", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "12/05", "title" => "اسفند روز، جشن اسفندگان، گرامی‌داشت زمین و بانوان / جشن برزگران", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "12/10", "title" => "جشن وخشنکام", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "12/19", "title" => "جشن نوروز رودها", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "12/20", "title" => "جشن گلدان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "12/25", "title" => "پایان سرایش شاهنامه فردوسی", "holiday" => false, "type" => "solar", 'importance' => 2],
    ["date" => "12/26", "title" => "فروردگان", "holiday" => false, "type" => "solar", 'importance' => 3],
    ["date" => "12/29", "title" => "روز ملی شدن صنعت نفت", "holiday" => true, "type" => "solar", 'importance' => 1],
    ["date" => "07/01", "title" => "ولادت امام محمد باقر علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "07/03", "title" => "شهادت امام علی النقی الهادی علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "07/10", "title" => "ولادت امام محمد تقی علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "07/13", "title" => "ولادت امام علی علیه السلام و روز پدر", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "07/15", "title" => "وفات حضرت زینب سلام الله علیها", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "07/25", "title" => "شهادت امام موسی کاظم علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "07/27", "title" => "مبعث رسول اکرم", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "08/03", "title" => "ولادت سالار شهیدان، امام حسین علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "08/04", "title" => "ولادت ابوالفضل العباس علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "08/05", "title" => "ولادت امام زین العابدین علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "08/11", "title" => "ولادت علی اکبر علیه السلام و روز جوان", "holiday" => false, "type" => "lunar", 'importance' => 2],
    ["date" => "08/15", "title" => "ولادت حضرت قائم عجل الله تعالی فرجه و جشن نیمه شعبان", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "09/15", "title" => "ولادت امام حسن مجتبی علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "09/18", "title" => "شب قدر", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "09/19", "title" => "ضربت خوردن حضرت علی علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "09/21", "title" => "شهادت حضرت علی علیه السلام", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "09/22", "title" => "شب قدر", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "10/02", "title" => "عید سعید فطر", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "10/03", "title" => "تعطیل به مناسبت عید سعید فطر", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "10/26", "title" => "شهادت امام جعفر صادق علیه السلام", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "11/02", "title" => "ولادت حضرت معصومه سلام الله علیها و روز دختران", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "11/12", "title" => "ولادت امام رضا علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "11/30", "title" => "شهادت امام محمد تقی علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "12/07", "title" => "شهادت امام محمد باقرعلیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "12/09", "title" => "روز عرفه", "holiday" => false, "type" => "lunar", 'importance' => 2],
    ["date" => "12/10", "title" => "عید سعید قربان", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "12/15", "title" => "ولادت امام علی النقی الهادی علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "12/18", "title" => "عید سعید غدیر خم", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "12/20", "title" => "ولادت امام موسی کاظم علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "01/10", "title" => "تاسوعای حسینی", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "01/11", "title" => "عاشورای حسینی", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "01/13", "title" => "شهادت امام زین العابدین علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "01/14", "title" => "شهادت امام زین العابدین علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "02/20", "title" => "اربعین حسینی", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "02/28", "title" => "رحلت رسول اکرم؛شهادت امام حسن مجتبی علیه السلام", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "02/28", "title" => "رحلت رسول اکرم؛شهادت امام حسن مجتبی علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "02/30", "title" => "شهادت امام رضا علیه السلام", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "03/01", "title" => "هجرت پیامبر اکرم از مکه به مدینه", "holiday" => false, "type" => "lunar", 'importance' => 2],
    ["date" => "03/09", "title" => "شهادت امام حسن عسکری علیه السلام", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "03/13", "title" => "میلاد رسول اکرم به روایت اهل سنت", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "03/18", "title" => "میلاد رسول اکرم و امام جعفر صادق علیه السلام", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "04/11", "title" => "وفات حضرت معصومه سلام الله علیها", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "05/06", "title" => "ولادت حضرت زینب سلام الله علیها و روز پرستار و بهورز", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "06/04", "title" => "شهادت حضرت فاطمه زهرا سلام الله علیها", "holiday" => true, "type" => "lunar", 'importance' => 1],
    ["date" => "06/21", "title" => "ولادت حضرت فاطمه زهرا سلام الله علیها و روز زن", "holiday" => false, "type" => "lunar", 'importance' => 1],
    ["date" => "06/30", "title" => "ولادت امام محمد باقر علیه السلام", "holiday" => false, "type" => "lunar", 'importance' => 1],
];
